config/routes.rb
WingmanFinder::Application.routes.draw do 
  get "home/about"

  get "home/careers"

  get "home/index"

  get "home/legal"

  get "home/contact"

  resources :bars

  resources :text_messages
  resources :users
  resources :user_sessions
  resources :politician_requests

  root :to => "home#index"
  
  get '/login' => 'user_sessions#new', as: :login
  
  get '/logout' => 'user_sessions#destroy', as: :logout

  match 'twilio/process_sms' => 'twilio#process_sms'
end

app/models/politician_request.rb
class PoliticianRequest < ActiveRecord::Base
	belongs_to :user
end

app/controllers/politician_requests_controller.rb
class PoliticianRequestsController < ApplicationController
  # GET /politician_requests
  # GET /politician_requests.json
  def index
    @politician_requests = PoliticianRequest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @politician_requests }
    end
  end

  # GET /politician_requests/1
  # GET /politician_requests/1.json
  def show
    @politician_request = PoliticianRequest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @politician_request }
    end
  end

  # GET /politician_requests/new
  # GET /politician_requests/new.json
  def new
    @politician_request = PoliticianRequest.new
    @user = @politician_request.user
    #@tracker_users = @politician_request.users.build


    respond_to do |format|
      format.html  
      format.json { render json: @politician_request }
    end
  end

  # GET /politician_requests/1/edit
  def edit
    @politician_request = PoliticianRequest.find(params[:id])
  end

  # POST /politician_requests
  # POST /politician_requests.json
  def create
    @politician_request = PoliticianRequest.new(params[:politician_request])
    the_id =  params[:user]
    lookup_id = the_id.to_i
    @politician_request.user_id = lookup_id

    respond_to do |format|
      if @politician_request.save
        format.html { redirect_to @politician_request, notice: 'Politician request was successfully created.' }
        format.json { render json: @politician_request, status: :created, location: @politician_request }
      else
        format.html { render action: "new" }
        format.json { render json: @politician_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /politician_requests/1
  # PUT /politician_requests/1.json
  def update
    @politician_request = PoliticianRequest.find(params[:id])

    respond_to do |format|
      if @politician_request.update_attributes(params[:politician_request])
        format.html { redirect_to @politician_request, notice: 'Politician request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @politician_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politician_requests/1
  # DELETE /politician_requests/1.json
  def destroy
    @politician_request = PoliticianRequest.find(params[:id])
    @politician_request.destroy

    respond_to do |format|
      format.html { redirect_to politician_requests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/politician_requests_helper.rb
module PoliticianRequestsHelper
end

app/views/politician_requests/_form.html.erb
<%= form_for(@politician_request) do |f| %>
  <% if @politician_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@politician_request.errors.count, "error") %> prohibited this politician_request from being saved:</h2>

      <ul>
      <% @politician_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :request %><br />
    <%= f.text_area :request %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <%# fields_for(@users) do |user_stuff|  %>
    <div class="field">
      <%#= user_stuff.label "Users"%><br />
      <%# = collection_select( :users, :id, User.all, :id, :name, {}, {:multiple => true})%> 
      <%= select_tag 'user', options_from_collection_for_select(User.where(:is_politician => true), :id, :name), multiple: false, size: '10%' %>
    </div>
  <%# end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/politician_requests/edit.html.erb
<h1>Editing politician_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @politician_request %> |
<%= link_to 'Back', politician_requests_path %>

app/views/politician_requests/index.html.erb
<h1>Listing politician_requests</h1>

<table>
  <tr>
    <th>Request</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @politician_requests.each do |politician_request| %>
  <tr>
    <td><%= politician_request.request %></td>
    <td><%= politician_request.email %></td>
    <td><%= link_to 'Show', politician_request %></td>
    <td><%= link_to 'Edit', edit_politician_request_path(politician_request) %></td>
    <td><%= link_to 'Destroy', politician_request, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Politician request', new_politician_request_path %>

app/views/politician_requests/new.html.erb
<h1>New politician_request</h1>

<%= render 'form' %>

<%= link_to 'Back', politician_requests_path %>

app/views/politician_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Request:</b>
  <%= @politician_request.request %>
</p>

<p>
  <b>Email:</b>
  <%= @politician_request.email %>
</p>


<%= link_to 'Edit', edit_politician_request_path(@politician_request) %> |
<%= link_to 'Back', politician_requests_path %>