config/routes.rb
WingmanFinder::Application.routes.draw do 
  get "home/about"

  get "home/careers"

  get "home/index"

  get "home/legal"

  get "home/contact"

  resources :bars

  resources :text_messages
  resources :users
  resources :user_sessions
  resources :politician_requests

  root :to => "home#index"
  
  get '/login' => 'user_sessions#new', as: :login
  
  get '/logout' => 'user_sessions#destroy', as: :logout

  match 'twilio/process_sms' => 'twilio#process_sms'
end

app/models/bar.rb
class Bar < ActiveRecord::Base
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bars }
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, notice: 'Bar was successfully created.' }
        format.json { render json: @bar, status: :created, location: @bar }
      else
        format.html { render action: "new" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/views/bars/_form.html.erb
<%= form_for(@bar) do |f| %>
  <% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
      <% @bar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bars/edit.html.erb
<h1>Editing bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar %> |
<%= link_to 'Back', bars_path %>

app/views/bars/index.html.erb
<h1>Listing bars</h1>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bars.each do |bar| %>
  <tr>
    <td><%= bar.name %></td>
    <td><%= bar.city %></td>
    <td><%= bar.state %></td>
    <td><%= link_to 'Show', bar %></td>
    <td><%= link_to 'Edit', edit_bar_path(bar) %></td>
    <td><%= link_to 'Destroy', bar, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bar', new_bar_path %>

app/views/bars/new.html.erb
<h1>New bar</h1>

<%= render 'form' %>

<%= link_to 'Back', bars_path %>

app/views/bars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bar.name %>
</p>

<p>
  <b>City:</b>
  <%= @bar.city %>
</p>

<p>
  <b>State:</b>
  <%= @bar.state %>
</p>


<%= link_to 'Edit', edit_bar_path(@bar) %> |
<%= link_to 'Back', bars_path %>