config/routes.rb
WingmanFinder::Application.routes.draw do 
  get "home/about"

  get "home/careers"

  get "home/index"

  get "home/legal"

  get "home/contact"

  resources :bars

  resources :text_messages
  resources :users
  resources :user_sessions
  resources :politician_requests

  root :to => "home#index"
  
  get '/login' => 'user_sessions#new', as: :login
  
  get '/logout' => 'user_sessions#destroy', as: :logout

  match 'twilio/process_sms' => 'twilio#process_sms'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def careers
  end

  def index
    
  end

  def legal
  end

  def contact
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/careers.html.erb
<h1>Home#careers</h1>
<p>Find me in app/views/home/careers.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<div class="header_wrap">
		<div class="logo">
			Gov<span>stream</span>
		</div>
		<p class="tag">political engagement redefined</p>
	</div>
	<div class="login_info">
		<div class="button_wrapper_s">
			<% if current_user %>
				<%= link_to "Edit Profile", edit_user_path(current_user), :class => "button_s" %>
	        	<%= link_to "Logout", logout_path, :class => "button_s" %>
	        	<% if current_user.is_politician %>
	        		<%= link_to "Send A Text Message", new_text_message_path, :class => "button_s" %>
	        		<table>
					  <tr>
					    <th>Request</th>
					    <th>Email</th>
					    <th></th>
					    <th></th>
					    <th></th>
					  </tr>

					<% PoliticianRequest.where(:user_id => current_user.id).each do |politician_request| %>
					  <tr>
					    <td><%= politician_request.request %></td>
					    <td><%= politician_request.email %></td>
					  </tr>
					<% end %>
					</table>
					<br />
	    		<% else %>
	    		| <%= link_to "Send a Request", new_politician_request_path, :class => "button_s" %>

	        		<table>
					  <tr>
					    <th>Message</th>
					    <th>Number</th>
					    <th></th>
					    <th></th>
					    <th></th>
					  </tr>

					<% TextMessage.where(:receiver => current_user.phone_number).each do |message| %>
					  <tr>
					    <td><%= message.content %></td>
					    <td><%= message.name %></td>
					  </tr>
					<% end %>
					</table>
					<br />
	    </div>
	        <% end %>
	   	<div class="not_logged">
	    <% else %>

	    		<div class="button_wrapper">
	        		<%= link_to "Sign up", new_user_path, :class => "button" %>
	        	</div>

	        	<p class="or">or <%= link_to "login", login_path %> if you're an existing user</p>
	    	<% end %>
	    </div>
	<div class="expo">
		<p>Govstream gives people the power to engage with politicians on a whole new level. With the power of sms texting you can get updates on what politicians are voting on and even send back messages to get your voice heard.</p>
	</div>

	<div class="phone">
		<%= image_tag("/assets/phone.png") %>
	</div>

app/views/home/legal.html.erb
<h1>Home#legal</h1>
<p>Find me in app/views/home/legal.html.erb</p>