config/routes.rb
WingmanFinder::Application.routes.draw do 
  get "home/about"

  get "home/careers"

  get "home/index"

  get "home/legal"

  get "home/contact"

  resources :bars

  resources :text_messages
  resources :users
  resources :user_sessions
  resources :politician_requests

  root :to => "home#index"
  
  get '/login' => 'user_sessions#new', as: :login
  
  get '/logout' => 'user_sessions#destroy', as: :logout

  match 'twilio/process_sms' => 'twilio#process_sms'
end

app/models/text_message.rb
class TextMessage < ActiveRecord::Base
end

app/controllers/text_messages_controller.rb
class TextMessagesController < ApplicationController
  # GET /text_messages
  # GET /text_messages.json
  def index
    @text_messages = TextMessage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @text_messages }
    end
  end

  # GET /text_messages/1
  # GET /text_messages/1.json
  def show
    @text_message = TextMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_message }
    end
  end

  # GET /text_messages/new
  # GET /text_messages/new.json
  def new
    @text_message = TextMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text_message }
    end
  end

  # GET /text_messages/1/edit
  def edit
    @text_message = TextMessage.find(params[:id])
  end

  # POST /text_messages
  # POST /text_messages.json
  def send_text_message(text_message)
    number_to_send_to = text_message.receiver
    message = text_message.content
    twilio_sid = "AC50070372767bdf26a090b08007bba07f"
    twilio_token = "8ae1cdbb08d55b99cab34174c3cd8bbb"
    twilio_phone_number = "2245209581"
    @twilio_client = Twilio::REST::Client.new twilio_sid, twilio_token
    @twilio_client.account.sms.messages.create(
      :from => "+1#{twilio_phone_number}",
      :to => number_to_send_to,
      :body => message
    )
    
  end

  def create
    puts "the numbers"
    puts "#{params[:receiver]}"
    the_array = params[:receiver]
    the_array.each do |this|
      @new_text_message = TextMessage.new
      @new_text_message.content = params["text_message"]["content"]
      @new_text_message.receiver = this
      send_text_message(@new_text_message)
    end
    @text_message = TextMessage.new(params[:text_message])
    @text_message.name = current_user.name
    @text_message.receiver = params[:receiver].first
    respond_to do |format|
      if @text_message.save
        phone_number = @text_message.receiver
        send_text_message(@text_message)
        format.html { redirect_to @text_message, notice: 'Text message was successfully created.' }
        format.json { render json: @text_message, status: :created, location: @text_message }
      else
        format.html { render action: "new" }
        format.json { render json: @text_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_messages/1
  # PUT /text_messages/1.json
  def update
    @text_message = TextMessage.find(params[:id])

    respond_to do |format|
      if @text_message.update_attributes(params[:text_message])
        format.html { redirect_to @text_message, notice: 'Text message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @text_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_messages/1
  # DELETE /text_messages/1.json
  def destroy
    @text_message = TextMessage.find(params[:id])
    @text_message.destroy

    respond_to do |format|
      format.html { redirect_to text_messages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/text_messages_helper.rb
module TextMessagesHelper
end

app/views/text_messages/_form.html.erb
<%= form_for(@text_message) do |f| %>
  <% if @text_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_message.errors.count, "error") %> prohibited this text_message from being saved:</h2>

      <ul>
      <% @text_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <!--<div class="field">
    <%#= f.label :receiver %><br />
    <%#= f.text_field :receiver %>
  </div> -->
  <div class="field">
  <%#= user_stuff.label "Users"%><br />
  <%# = collection_select( :users, :id, User.all, :id, :name, {}, {:multiple => true})%> 
  <%= select_tag 'receiver', options_from_collection_for_select(User.all, :phone_number, :name), multiple: true, size: '10%' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_messages/edit.html.erb
<h1>Editing text_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_message %> |
<%= link_to 'Back', text_messages_path %>

app/views/text_messages/index.html.erb
<h1>Listing text_messages</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Sender</th>
    <th>Receiver</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @text_messages.each do |text_message| %>
  <tr>
    <td><%= text_message.content %></td>
    <td><%= text_message.receiver %></td>
    <td><%= link_to 'Show', text_message %></td>
    <td><%= link_to 'Edit', edit_text_message_path(text_message) %></td>
    <td><%= link_to 'Destroy', text_message, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Text message', new_text_message_path %>

app/views/text_messages/new.html.erb
<div id="users">
<h1>New text message</h1>

<%= render 'form' %>

<!-- <%= link_to 'Back', text_messages_path %> -->
</div>

app/views/text_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @text_message.content %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @text_message.receiver %>
</p>

<!-- 
<%= link_to 'Edit', edit_text_message_path(@text_message) %> |
<%= link_to 'strongack', text_messages_path %> -->